"use client";

export const dynamic = "force-dynamic";

import { useEffect, useState, use } from "react";
import { useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase";
import { AuthProvider, useAuth } from "@/components/AuthProvider";
import Link from "next/link";
import type { Tournament, Category, Entry, Match as MatchType } from "@/lib/types";
import { autoGenerateDraw, type DrawEntry } from "@/lib/drawEngine";

let _supabase: ReturnType<typeof createClient> | null = null;
function getSupabase() {
  if (!_supabase) _supabase = createClient();
  return _supabase;
}

export default function TournamentDetailPage({
  params,
}: {
  params: Promise<{ tournamentId: string }>;
}) {
  const { tournamentId } = use(params);
  const { session, loading: authLoading } = useAuth();
  const router = useRouter();
  const supabase = getSupabase();

  const [tournament, setTournament] = useState<Tournament | null>(null);
  const [categories, setCategories] = useState<Category[]>([]);
  const [entries, setEntries] = useState<Entry[]>([]);
  const [matches, setMatches] = useState<MatchType[]>([]);
  const [activeTab, setActiveTab] = useState<"overview" | "entries" | "draw" | "matches">("overview");
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    if (!authLoading && !session) router.push("/auth/login");
  }, [session, authLoading]);

  useEffect(() => {
    if (!session || !tournamentId) return;
    loadAll();
  }, [session, tournamentId]);

  async function loadAll() {
    setLoading(true);
    const { data: t } = await supabase.from("tournaments").select("*").eq("id", tournamentId).single();
    setTournament(t as Tournament);
    const { data: cats } = await supabase.from("categories").select("*").eq("tournament_id", tournamentId);
    setCategories(cats as Category[] || []);
    const { data: ents } = await supabase.from("entries").select("*");
    const filtered = (ents as Entry[] || []).filter(e => categories.some(c => c.id === e.category_id));
    setEntries(filtered);
    const { data: m } = await supabase.from("matches").select("*").eq("tournament_id", tournamentId);
    setMatches(m as MatchType[] || []);
    setLoading(false);
  }

  async function publishTournament() {
    if (!tournament) return;
    await supabase.from("tournaments").update({ status: "published" }).eq("id", tournamentId);
    setTournament({ ...tournament, status: "published" });
  }

  async function generateDraw() {
    if (!tournament || categories.length === 0) return;

    for (const cat of categories) {
      const catEntries = entries.filter((e) => e.category_id === cat.id);
      if (catEntries.length < 2) continue;

      const drawEntries: DrawEntry[] = catEntries.map((e, idx) => ({
        entry_id: e.id,
        name: e.player_1_id,
        seed: e.seed || undefined,
      }));

      const draw = autoGenerateDraw(drawEntries);
      const matchInserts = draw.matches.map((dm) => ({
        tournament_id: tournamentId,
        category_id: cat.id,
        entry_1_id: dm.entry_1_id,
        entry_2_id: dm.entry_2_id,
        next_match_id: dm.next_match_id,
        round: dm.round,
        match_number: dm.match_number,
        status: "scheduled" as const,
        court_name: dm.court_number ? `Court ${dm.court_number}` : null,
      }));

      await supabase.from("matches").insert(matchInserts);
    }

    await supabase.from("tournaments").update({ status: "live" }).eq("id", tournamentId);
    setTournament({ ...tournament, status: "live" });
    await loadAll();
  }

  if (authLoading || loading) return <div className="min-h-screen flex items-center justify-center"><div className="animate-spin w-8 h-8 border-4 border-emerald-500 border-t-transparent rounded-full" /></div>;
  if (!session || !tournament) return null;

  const isOwner = tournament.organizer_id === session.user.id;

  return (
    <div className="min-h-screen bg-gray-50">
      <nav className="bg-emerald-900 text-white px-6 py-4">
        <Link href="/organizer" className="text-sm text-emerald-200 hover:text-emerald-100">← Dashboard</Link>
      </nav>

      <div className="max-w-6xl mx-auto px-6 py-8">
        {/* Header */}
        <div className="bg-white rounded-2xl p-8 border border-gray-100 shadow-sm mb-6">
          <div className="flex items-center justify-between">
            <div>
              <h1 className="text-3xl font-black text-gray-900">{tournament.name}</h1>
              <div className="flex items-center gap-2 mt-2">
                <span className={`px-3 py-1 rounded-full text-xs font-bold ${
                  tournament.status === "draft" ? "bg-gray-100 text-gray-600" :
                  tournament.status === "published" ? "bg-blue-100 text-blue-700" :
                  tournament.status === "live" ? "bg-green-100 text-green-700" :
                  "bg-purple-100 text-purple-700"
                }`}>
                  {tournament.status}
                </span>
                {tournament.location && <span className="text-sm text-gray-400">📍 {tournament.location}</span>}
                <span className="text-sm text-gray-400">{tournament.start_date?.slice(0, 10)}</span>
              </div>
            </div>
            <div className="flex gap-3">
              {tournament.status === "draft" && isOwner && (
                <button onClick={publishTournament} className="bg-blue-600 text-white px-5 py-2.5 rounded-xl font-bold text-sm hover:bg-blue-500">Publish</button>
              )}
              {tournament.status === "published" && isOwner && (
                <button onClick={generateDraw} className="bg-emerald-700 text-white px-5 py-2.5 rounded-xl font-bold text-sm hover:bg-emerald-600">🎲 Generate Draw</button>
              )}
              <button onClick={() => {
                navigator.clipboard.writeText(`${window.location.origin}/tournament/${tournamentId}`);
              }} className="border border-gray-200 text-gray-700 px-5 py-2.5 rounded-xl font-medium text-sm hover:bg-gray-50">Copy Link</button>
            </div>
          </div>
          {tournament.description && <p className="text-gray-500 mt-4">{tournament.description}</p>}
        </div>

        {/* Tabs */}
        <div className="flex gap-1 bg-white rounded-xl p-1 border border-gray-100 shadow-sm mb-6">
          {(["overview", "entries", "draw", "matches"] as const).map((tab) => (
            <button key={tab} onClick={() => setActiveTab(tab)}
              className={`flex-1 py-3 rounded-lg text-sm font-medium transition-all ${
                activeTab === tab ? "bg-emerald-700 text-white" : "text-gray-500 hover:text-gray-900"
              }`}>
              {tab === "overview" ? "Overview" : tab === "entries" ? `Players (${entries.length})` : tab === "draw" ? "Draw" : "Matches"}
            </button>
          ))}
        </div>

        {/* Tab Content */}
        {activeTab === "overview" && (
          <div className="bg-white rounded-2xl p-8 border border-gray-100 shadow-sm">
            <h2 className="text-lg font-bold text-gray-900 mb-4">Tournament Details</h2>
            <div className="grid grid-cols-2 md:grid-cols-4 gap-6">
              <div className="bg-gray-50 rounded-xl p-4 text-center">
                <div className="text-2xl font-black text-emerald-700">{categories.length}</div>
                <div className="text-sm text-gray-500">Categories</div>
              </div>
              <div className="bg-gray-50 rounded-xl p-4 text-center">
                <div className="text-2xl font-black text-blue-700">{entries.length}</div>
                <div className="text-sm text-gray-500">Players Entered</div>
              </div>
              <div className="bg-gray-50 rounded-xl p-4 text-center">
                <div className="text-2xl font-black text-purple-700">{matches.length}</div>
                <div className="text-sm text-gray-500">Matches</div>
              </div>
              <div className="bg-gray-50 rounded-xl p-4 text-center">
                <div className="text-2xl font-black text-orange-700">
                  {matches.filter((m) => m.status === "completed").length}
                </div>
                <div className="text-sm text-gray-500">Completed</div>
              </div>
            </div>
          </div>
        )}

        {activeTab === "entries" && (
          <div className="bg-white rounded-2xl border border-gray-100 shadow-sm overflow-hidden">
            <div className="px-6 py-4 border-b border-gray-100">
              <h2 className="font-bold text-gray-900">Player Entries</h2>
            </div>
            {entries.length > 0 ? (
              <table className="w-full text-sm">
                <thead className="bg-gray-50 text-gray-500">
                  <tr>
                    <th className="text-left px-6 py-3 font-medium">Player</th>
                    <th className="text-left px-6 py-3 font-medium">Category</th>
                    <th className="text-left px-6 py-3 font-medium">Seed</th>
                  </tr>
                </thead>
                <tbody>
                  {entries.map((e) => {
                    const cat = categories.find((c) => c.id === e.category_id);
                    return (
                      <tr key={e.id} className="border-t border-gray-50 hover:bg-gray-50">
                        <td className="px-6 py-3 font-medium text-gray-900">{e.player_1_id?.slice(0, 8)}</td>
                        <td className="px-6 py-3 text-gray-500">{cat?.name || "?"}</td>
                        <td className="px-6 py-3 text-gray-400">{e.seed ? `#${e.seed}` : "-"}</td>
                      </tr>
                    );
                  })}
                </tbody>
              </table>
            ) : (
              <div className="text-center py-12 text-gray-400">
                <div className="text-4xl mb-2">👥</div>
                <p>No entries yet. Share the tournament link for players to register.</p>
              </div>
            )}
          </div>
        )}

        {activeTab === "draw" && (
          <div className="bg-white rounded-2xl p-8 border border-gray-100 shadow-sm">
            <h2 className="text-lg font-bold text-gray-900 mb-4">Draw / Bracket</h2>
            {matches.length === 0 ? (
              <div className="text-center py-12 text-gray-400">
                <div className="text-4xl mb-2">🎲</div>
                <p>Draw not generated yet. Register players first, then generate the draw.</p>
              </div>
            ) : (
              <div className="space-y-2">
                {matches.map((m) => (
                  <div key={m.id} className="flex items-center justify-between bg-gray-50 rounded-xl px-4 py-3">
                    <div className="flex items-center gap-3">
                      <span className="text-xs text-gray-400 font-mono">#{m.match_number}</span>
                      <span className="text-xs font-medium text-gray-500 bg-gray-200 px-2 py-0.5 rounded">{m.round}</span>
                      <span className="font-medium text-gray-900">{m.entry_1_id?.slice(0, 8) || "TBD"}</span>
                      <span className="text-gray-400">vs</span>
                      <span className="font-medium text-gray-900">{m.entry_2_id?.slice(0, 8) || "TBD"}</span>
                    </div>
                    <div className="flex items-center gap-3">
                      <span className="text-xs text-gray-400">{m.court_name}</span>
                      <span className={`px-3 py-1 rounded-full text-xs font-medium ${
                        m.status === "playing" ? "bg-green-100 text-green-700" :
                        m.status === "completed" ? "bg-purple-100 text-purple-700" :
                        "bg-gray-100 text-gray-500"
                      }`}>{m.status}</span>
                    </div>
                  </div>
                ))}
              </div>
            )}
          </div>
        )}

        {activeTab === "matches" && (
          <div className="bg-white rounded-2xl p-8 border border-gray-100 shadow-sm">
            <h2 className="text-lg font-bold text-gray-900 mb-4">Live Matches</h2>
            {categories.map((cat) => {
              const catMatches = matches.filter((m) => m.category_id === cat.id);
              if (catMatches.length === 0) return null;
              return (
                <div key={cat.id} className="mb-6">
                  <h3 className="font-semibold text-gray-700 mb-3">{cat.name}</h3>
                  <div className="space-y-2">
                    {catMatches.map((m) => (
                      <div key={m.id} className="flex items-center justify-between bg-gray-50 rounded-xl px-4 py-3">
                        <div className="flex items-center gap-3">
                          <span className="font-medium text-gray-900">{m.entry_1_id?.slice(0, 8) || "TBD"}</span>
                          <span className="text-gray-400">vs</span>
                          <span className="font-medium text-gray-900">{m.entry_2_id?.slice(0, 8) || "TBD"}</span>
                        </div>
                        <Link href={`/umpire/${m.id}`}
                          className="text-sm bg-emerald-700 text-white px-4 py-2 rounded-lg hover:bg-emerald-600">
                          Open Umpire Pad
                        </Link>
                      </div>
                    ))}
                  </div>
                </div>
              );
            })}
          </div>
        )}
      </div>
    </div>
  );
}
