/**
 * TUAH2 Auto-Draw Engine (ported from TUAH1)
 */

export interface DrawEntry {
  entry_id: string;
  name: string;
  seed?: number;
}

export interface DrawMatch {
  match_number: number;
  round: string;
  round_index: number;
  entry_1_id: string | null;
  entry_2_id: string | null;
  court_number: number;
  next_match_id: string | null;
}

function getRoundName(rIdx: number, bracketSize: number): string {
  const matchesInRound = bracketSize / Math.pow(2, rIdx);
  if (matchesInRound === 1) return "Final";
  if (matchesInRound === 2) return "SF";
  if (matchesInRound === 4) return "QF";
  if (matchesInRound === 8) return "R16";
  if (matchesInRound === 16) return "R32";
  if (matchesInRound === 32) return "R64";
  return `Round ${rIdx + 1}`;
}

function generateSeedOrder(size: number): number[] {
  if (size === 1) return [1];
  if (size === 2) return [1, 2];
  let order = [1, 2];
  for (let r = 4; r <= size; r *= 2) {
    const next: number[] = [];
    for (let i = 0; i < order.length; i++) {
      next.push(order[i]);
      next.push(r + 1 - order[i]);
    }
    order = next;
  }
  return order;
}

export function generateKnockoutBracket(entries: DrawEntry[]): DrawMatch[] {
  const sorted = [...entries].sort((a, b) => {
    if (a.seed && b.seed) return a.seed - b.seed;
    if (a.seed) return -1;
    if (b.seed) return 1;
    return 0;
  });

  const size = Math.pow(2, Math.ceil(Math.log2(sorted.length)));
  const seedOrder = generateSeedOrder(size);

  const positions: (DrawEntry | null)[] = new Array(size).fill(null);
  for (let i = 0; i < sorted.length; i++) {
    const posIndex = seedOrder.indexOf(i + 1);
    if (posIndex !== -1 && posIndex < size) {
      positions[posIndex] = sorted[i];
    } else {
      const idx = positions.indexOf(null);
      if (idx !== -1) positions[idx] = sorted[i];
    }
  }

  const firstRound: { e1: DrawEntry | null; e2: DrawEntry | null }[] = [];
  for (let i = 0; i < size; i += 2) {
    firstRound.push({ e1: positions[i], e2: positions[i + 1] });
  }

  const roundInfo: { start: number; count: number; rIdx: number }[] = [];
  let totalMatches = size / 2;
  let startNum = 1;
  let ri = 0;
  while (totalMatches >= 1) {
    roundInfo.push({ start: startNum, count: totalMatches, rIdx: ri });
    startNum += totalMatches;
    totalMatches = Math.ceil(totalMatches / 2);
    ri++;
  }

  const matches: DrawMatch[] = [];
  for (const ri of roundInfo) {
    const { start, count } = ri;
    for (let i = 0; i < count; i++) {
      const matchNum = start + i;
      const roundName = getRoundName(ri.rIdx, size);
      let nextMatchId: string | null = null;
      const parentRound = roundInfo.find((r) => r.rIdx === ri.rIdx + 1);
      if (parentRound) {
        const parentIdx = Math.floor(i / 2);
        nextMatchId = `next:${parentRound.start + parentIdx}`;
      }
      let e1: string | null = null;
      let e2: string | null = null;
      if (ri.rIdx === 0) {
        e1 = firstRound[i]?.e1?.entry_id || null;
        e2 = firstRound[i]?.e2?.entry_id || null;
      }
      matches.push({
        match_number: matchNum,
        round: roundName,
        round_index: ri.rIdx,
        entry_1_id: e1,
        entry_2_id: e2,
        court_number: (matchNum % 10) + 1,
        next_match_id: nextMatchId,
      });
    }
  }
  return matches;
}

export function generateRoundRobin(entries: DrawEntry[]): DrawMatch[] {
  const n = entries.length;
  const matches: DrawMatch[] = [];
  let matchNum = 1;
  for (let i = 0; i < n; i++) {
    for (let j = i + 1; j < n; j++) {
      matches.push({
        match_number: matchNum,
        round: "Round Robin",
        round_index: 0,
        entry_1_id: entries[i].entry_id,
        entry_2_id: entries[j].entry_id,
        court_number: (matchNum % 10) + 1,
        next_match_id: null,
      });
      matchNum++;
    }
  }
  return matches;
}

export function autoGenerateDraw(entries: DrawEntry[]): {
  type: "round-robin" | "knockout";
  matches: DrawMatch[];
} {
  if (entries.length <= 4) {
    return { type: "round-robin", matches: generateRoundRobin(entries) };
  }
  return { type: "knockout", matches: generateKnockoutBracket(entries) };
}
