import { NextRequest, NextResponse } from "next/server";
import { verifyToken, getCookieName } from "@/lib/auth";
import { query, queryAll, queryOne } from "@/lib/db";
import {
  autoGenerateDraw,
  type DrawFormatType,
  type DrawEntry,
} from "@/lib/drawEngine";

export async function POST(
  req: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  const { id } = await params;

  const cookie = req.cookies.get(getCookieName())?.value;
  if (!cookie) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const payload = await verifyToken(cookie);
  if (!payload) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  try {
    // Verify ownership
    const tournCheck = await query(
      `SELECT organizer_id, status, number_of_courts FROM tournaments WHERE id = $1`,
      [id]
    );
    if (tournCheck.rows.length === 0) {
      return NextResponse.json({ error: "Tournament not found" }, { status: 404 });
    }
    if (tournCheck.rows[0].organizer_id !== payload.userId) {
      return NextResponse.json({ error: "Not your tournament" }, { status: 403 });
    }

    const numCourts = tournCheck.rows[0].number_of_courts || 4;

    // Parse request body for draw options
    const body = await req.json().catch(() => ({}));
    // #6 fix: keep requested format separate from the default so a re-draw
    // with an explicit body.format actually switches the bracket structure.
    const requestedFormat: DrawFormatType | undefined = body.format;
    const drawFormat: DrawFormatType = body.format || 'knockout';
    const swissRounds: number | undefined = body.swiss_rounds;
    const numGroups: number | undefined = body.groups;
    const advancePerGroup: number | undefined = body.advance;
    const separationRounds: number | undefined = body.separation_rounds;

    // Validate draw format
    const validFormats: DrawFormatType[] = [
      'knockout', 'round_robin', 'swiss', 'double_elimination',
      'group_knockout', 'manual', 'protected', 'club_separation',
    ];
    if (!validFormats.includes(drawFormat)) {
      return NextResponse.json({ error: `Invalid draw format: ${drawFormat}` }, { status: 400 });
    }

    const categories = await queryAll(
      `SELECT * FROM categories WHERE tournament_id = $1 ORDER BY name`,
      [id]
    );

    const allMatches: any[] = [];

    for (const cat of categories) {
      const catConfig = cat.scoring_config;
      let catFormat: DrawFormatType | null = null;

      if (catConfig) {
        const parsedConfig = typeof catConfig === 'string' ? JSON.parse(catConfig) : catConfig;
        // #6 fix: explicit request format overrides persisted format;
        // persist only when request omits format (keep downstream reads consistent).
        catFormat = requestedFormat ?? (parsedConfig.format as DrawFormatType | undefined) ?? drawFormat;
      } else {
        catFormat = requestedFormat ?? drawFormat;
      }

      // Fetch entries with player info including club for protected/club draw types
      const catEntries = await queryAll(
        `SELECT e.*, p1.full_name as p1_name, p2.full_name as p2_name, p1.club as p1_club
         FROM entries e
         LEFT JOIN profiles p1 ON p1.id = e.player_1_id
         LEFT JOIN profiles p2 ON p2.id = e.player_2_id
         WHERE e.category_id = $1 AND e.status != 'withdrawn'`,
        [cat.id]
      );

      if (catEntries.length < 2) {
        // Still create matches if manual draw (empty slots are allowed)
        if (drawFormat !== 'manual') continue;
      }

      // #47: Group+KO validation (advance <= min group size, sensible groups)
      if (catFormat === 'group_knockout' && catEntries.length >= 2) {
        const nEntries = catEntries.length;
        const g = numGroups ?? Math.max(1, Math.min(4, Math.floor(nEntries / 4)));
        const a = advancePerGroup ?? 2;
        if (g < 1) {
          return NextResponse.json({ error: "groups must be at least 1" }, { status: 400 });
        }
        if (g > nEntries) {
          return NextResponse.json({ error: `groups (${g}) exceeds entries (${nEntries}) in category ${cat.name}` }, { status: 400 });
        }
        const baseSize = Math.floor(nEntries / g);
        if (baseSize < 1) {
          return NextResponse.json({ error: `Not enough entries for ${g} groups in category ${cat.name}` }, { status: 400 });
        }
        if (a < 1) {
          return NextResponse.json({ error: "advance must be at least 1" }, { status: 400 });
        }
        if (a > baseSize) {
          return NextResponse.json({ error: `advance (${a}) exceeds minimum group size (${baseSize} per group) in category ${cat.name}` }, { status: 400 });
        }
      }

      // Build entry list with club info
      const drawEntries: DrawEntry[] = catEntries.map((e: any) => ({
        entry_id: e.id,
        name: e.p2_name ? `${e.p1_name} / ${e.p2_name}` : e.p1_name || e.id.slice(0, 8),
        seed: e.seed != null ? Number(e.seed) : undefined,
        club: e.p1_club || null,
      }));

      // If no entries for manual, still create placeholder
      if (drawEntries.length === 0 && drawFormat === 'manual') {
        // Nothing to do, skip category
        continue;
      }

      // Delete existing matches for this category (regenerate)
      await query(
        `DELETE FROM matches WHERE category_id = $1`,
        [cat.id]
      );

      // Persist the category's draw format (+ GK options) so downstream
      // consumers (standings API, bracket UI) can always read it.
      {
        const parsedConfig = catConfig
          ? (typeof catConfig === 'string' ? JSON.parse(catConfig) : catConfig)
          : {};
        const merged = {
          ...(parsedConfig && typeof parsedConfig === 'object' ? parsedConfig : {}),
          format: catFormat,
        };
        if (catFormat === 'group_knockout') {
          merged.numGroups = numGroups ?? Math.max(1, Math.min(4, Math.floor(catEntries.length / 4)));
          merged.advance = advancePerGroup ?? 2;
        }
        await query(
          `UPDATE categories SET scoring_config = $1::jsonb WHERE id = $2`,
          [JSON.stringify(merged), cat.id]
        );
      }

      // Route to the appropriate engine function
      const draw = autoGenerateDraw(drawEntries, catFormat, {
        swissRounds,
        numGroups,
        advancePerGroup,
        separationRounds,
        courtCount: numCourts,
      });

      // Phase 1: Insert all matches without next_match_id
      const inserted: any[] = [];
      for (const dm of draw.matches) {
        const res = await query(
          `INSERT INTO matches (tournament_id, category_id, entry_1_id, entry_2_id, round, match_number, status, court_number, next_match_id, loser_match_id, bracket_group, round_index)
           VALUES ($1, $2, $3, $4, $5, $6, $7, $8, NULL, NULL, $9, $10) RETURNING *`,
          [
            id,
            cat.id,
            dm.entry_1_id || null,
            dm.entry_2_id || null,
            dm.round || "Round 1",
            dm.match_number || 1,
            "scheduled",
            (dm.court_number || 0),
            dm.bracket_group || null,
            dm.round_index ?? null,
          ]
        );
        inserted.push({ ...dm, db_id: res.rows[0].id });
        allMatches.push(res.rows[0]);
      }

      // Phase 2: Update next_match_id / loser_match_id with actual UUIDs
      for (const match of inserted) {
        if (match.next_match_id && typeof match.next_match_id === "string" && match.next_match_id.startsWith("next:")) {
          const targetNum = parseInt(match.next_match_id.replace("next:", ""), 10);
          const target = inserted.find((m) => m.match_number === targetNum);
          if (target) {
            await query(
              `UPDATE matches SET next_match_id = $1 WHERE id = $2`,
              [target.db_id, match.db_id]
            );
          }
        }
        // #49: resolve loser:N -> loser_match_id (double elimination)
        if (match.loser_match_id && typeof match.loser_match_id === "string" && match.loser_match_id.startsWith("loser:")) {
          const targetNum = parseInt(match.loser_match_id.replace("loser:", ""), 10);
          const target = inserted.find((m) => m.match_number === targetNum);
          if (target) {
            await query(
              `UPDATE matches SET loser_match_id = $1 WHERE id = $2`,
              [target.db_id, match.db_id]
            );
          }
        }
      }

      // Phase 3: BYE matches are auto-completed. A bye match has exactly one
      // real entry (the other side is NULL). Mark it completed with the real
      // player as winner and auto-advance that winner into the next round, so
      // the bracket stays fully playable for non-power-of-2 player counts.
      for (const match of inserted) {
        const hasE1 = !!match.entry_1_id;
        const hasE2 = !!match.entry_2_id;
        if (hasE1 !== hasE2) { // exactly one side filled = bye match
          const byeWinner = hasE1 ? match.entry_1_id : match.entry_2_id;
          await query(
            `UPDATE matches SET status = 'completed', winner_entry_id = $1, updated_at = now() WHERE id = $2`,
            [byeWinner, match.db_id]
          );
          // Auto-advance winner into next match slot
          if (match.next_match_id && typeof match.next_match_id === "string" && match.next_match_id.startsWith("next:")) {
            const targetNum = parseInt(match.next_match_id.replace("next:", ""), 10);
            const target = inserted.find((m) => m.match_number === targetNum);
            if (target) {
              const roundMatches = inserted
                .filter((m) => m.round === match.round)
                .sort((a, b) => a.match_number - b.match_number);
              const idxInRound = roundMatches.findIndex((m) => m.db_id === match.db_id);
              if (idxInRound !== -1) {
                const slotField = idxInRound % 2 === 0 ? 'entry_1_id' : 'entry_2_id';
                await query(
                  `UPDATE matches SET ${slotField} = $1 WHERE id = $2`,
                  [byeWinner, target.db_id]
                );
              }
            }
          }
        }
      }
    }

    // Update tournament status to in_progress
    await query(
      `UPDATE tournaments SET status = 'in_progress', updated_at = now() WHERE id = $1`,
      [id]
    );

    return NextResponse.json({
      success: true,
      matches_created: allMatches.length,
      draw_type: drawFormat,
      message: `${drawFormat.replace(/_/g, ' ')} draw generated with ${allMatches.length} matches`,
    });
  } catch (err: any) {
    console.error("Draw generation error:", err);
    return NextResponse.json({ error: err.message || "Failed to generate draw" }, { status: 500 });
  }
}
