import { NextRequest, NextResponse } from "next/server";
import { verifyToken, getCookieName } from "@/lib/auth";
import { query, queryAll, queryOne } from "@/lib/db";

// POST /api/tournaments/[id]/schedule â€” P1-006 auto court + time scheduling
//
// APPROVED SCOPE (Gan 2026-08-08): uses ONLY existing columns
//   matches.court_number / matches.scheduled_time / tournaments.number_of_courts.
// - Assigns court + time slot to every match of THIS tournament that has
//   status='scheduled' AND scheduled_time IS NULL (empty slots only).
// - Different courts may host matches at the same time slot.
// - Same court + same time slot overlap -> 409 (conflict is never generated by
//   this endpoint; it 409s if a pre-existing manual assignment blocks placement).
// - Idempotent: matches that already have scheduled_time are never overwritten.
// - No new tables, no /api/venues (venue marketplace domain is out of scope).
export async function POST(
  req: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  const { id } = await params;
  if (!/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(id)) {
    return NextResponse.json({ error: "Tournament not found" }, { status: 404 });
  }

  const cookie = req.cookies.get(getCookieName())?.value;
  if (!cookie) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  const payload = await verifyToken(cookie);
  if (!payload) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  try {
    const tournament = await queryOne(
      `SELECT id, organizer_id, status, number_of_courts, start_date, end_date, registration_deadline
       FROM tournaments WHERE id = $1`,
      [id]
    );
    if (!tournament) return NextResponse.json({ error: "Tournament not found" }, { status: 404 });
    if (tournament.organizer_id !== payload.userId && payload.role !== 'admin') {
      return NextResponse.json({ error: "Forbidden â€” not your tournament" }, { status: 403 });
    }

    const body = await req.json().catch(() => ({}));

    // Options (validated, defaults safe)
    const numCourts = Math.max(1, Number(tournament.number_of_courts) || 4);
    let matchDurationMin = body.match_duration_min ?? body.matchDurationMin ?? 30;
    matchDurationMin = Number(matchDurationMin);
    if (!Number.isInteger(matchDurationMin) || matchDurationMin < 5 || matchDurationMin > 180) {
      return NextResponse.json({ error: "match_duration_min must be an integer between 5 and 180" }, { status: 400 });
    }

    // Base start time: explicit body.start_time (ISO or "HH:MM") > registration_deadline (future) > start_date 09:00 +08 > now
    // BUG-NEW-01/#36: pg returns Postgres DATE as a JS Date at server-local midnight (+08).
    // .toISOString() shifts to UTC -> previous calendar day (off-by-one). Extract the
    // calendar date in Asia/Kuala_Lumpur (+08) explicitly. No server-TZ change.
    const toLocalDateStr = (v: unknown): string => {
      if (!v) return "";
      const d = v instanceof Date ? v : new Date(String(v));
      if (isNaN(d.getTime())) return String(v).slice(0, 10);
      const parts = new Intl.DateTimeFormat("en-CA", {
        timeZone: "Asia/Kuala_Lumpur",
        year: "numeric",
        month: "2-digit",
        day: "2-digit",
      }).formatToParts(d);
      const p: Record<string, string> = {};
      for (const part of parts) p[part.type] = part.value;
      return `${p.year}-${p.month}-${p.day}`;
    };
    const startDateStr = toLocalDateStr(tournament.start_date);
    let baseTime: Date;
    const explicitStart = body.start_time ?? body.startTime;
    if (explicitStart) {
      if (/^\d{2}:\d{2}$/.test(String(explicitStart))) {
        baseTime = new Date(`${startDateStr}T${explicitStart}:00+08:00`);
      } else {
        baseTime = new Date(String(explicitStart));
      }
      if (isNaN(baseTime.getTime())) {
        return NextResponse.json({ error: "start_time must be ISO timestamp or HH:MM" }, { status: 400 });
      }
    } else {
      baseTime = new Date(`${startDateStr}T09:00:00+08:00`);
      if (tournament.registration_deadline && new Date(tournament.registration_deadline).getTime() > Date.now()) {
        baseTime = new Date(tournament.registration_deadline);
      }
    }
    const now = new Date();
    if (baseTime.getTime() < now.getTime()) {
      baseTime = now;
    }

    // All matches of this tournament: keep already-scheduled untouched (idempotent)
    const allMatches = await queryAll(
      `SELECT id, match_number, court_number, scheduled_time, status FROM matches
       WHERE tournament_id = $1 ORDER BY match_number`,
      [id]
    );
    const emptySlots = allMatches.filter(
      (m: any) => m.status === 'scheduled' && (m.scheduled_time === null || m.scheduled_time === undefined)
    );
    const alreadyScheduled = allMatches.length - emptySlots.length;

    if (emptySlots.length === 0) {
      return NextResponse.json({
        scheduled: 0,
        skipped: alreadyScheduled,
        total: allMatches.length,
        message: "No empty slots to schedule (all matches already have a scheduled_time)",
      });
    }

    // Occupied (court, time) set from existing assignments â€” conflict detection
    const used = new Set<string>();
    for (const m of allMatches) {
      if (m.scheduled_time) {
        used.add(`${m.court_number}|${new Date(m.scheduled_time).toISOString()}`);
      }
    }

    const durationMs = matchDurationMin * 60 * 1000;
    const schedule: { match_id: string; match_number: number; court_number: number; scheduled_time: string }[] = [];

    // Fill earliest slots first (k = slot index, courts 1..n in parallel).
    // Deterministic; never generates same-court/same-time overlap; scans forward
    // past any pre-existing manual assignment that already occupies a slot.
    let k = 0;
    for (const m of emptySlots) {
      let placed = false;
      // keep scanning slot rows until this match fits
      while (!placed) {
        for (let c = 1; c <= numCourts; c++) {
          const t = new Date(baseTime.getTime() + k * durationMs);
          const key = `${c}|${t.toISOString()}`;
          if (!used.has(key)) {
            used.add(key);
            schedule.push({
              match_id: m.id,
              match_number: m.match_number,
              court_number: c,
              scheduled_time: t.toISOString(),
            });
            placed = true;
            break;
          }
        }
        if (!placed) k++;
        if (k > 100000) {
          // unreachable in practice: no free slot in the entire timeline
          return NextResponse.json(
            { error: "Schedule conflict: no free court/time slot available (existing assignments block all slots)" },
            { status: 409 }
          );
        }
      }
    }

    // Persist (single pass, only empty slots)
    for (const s of schedule) {
      await query(
        `UPDATE matches SET court_number = $1, scheduled_time = $2, updated_at = now() WHERE id = $3`,
        [s.court_number, s.scheduled_time, s.match_id]
      );
    }

    return NextResponse.json({
      scheduled: schedule.length,
      skipped: alreadyScheduled,
      total: allMatches.length,
      num_courts: numCourts,
      match_duration_min: matchDurationMin,
      base_time: baseTime.toISOString(),
      schedule,
    });
  } catch (err: any) {
    console.error("Schedule error:", err);
    return NextResponse.json({ error: "Failed to schedule matches" }, { status: 500 });
  }
}
